version: '3.7'

networks:
  application:
    driver: bridge

services:
  php-fpm:
    build:
      context: .
      dockerfile: './build/Dockerfile'
    networks:
      - application
    depends_on:
      - redis
    volumes:
      - .:/web

  nginx:
    image: nginx:latest
    depends_on:
      - php-fpm
    networks:
      - application
    ports:
      - '80:80'
    volumes:
      - .:/web
      - ./build/nginx:/etc/nginx/conf.d
  redis:
    image: redis:latest
    networks:
      - application
